language: python
python:
- '3.6'
before_install:
- openssl aes-256-cbc -K $encrypted_08e66fafa730_key -iv $encrypted_08e66fafa730_iv -in mcserver-service-account-key.json.enc -out mod-managing/mcserver-service-account-key.json -d
install:
- pip install -r requirements.txt
script:
- cd mod-managing
- python upload-mods.py
