language: python
python:
- '3.6'
install:
- openssl aes-256-cbc -K $encrypted_9112fb2807d4_key -iv $encrypted_9112fb2807d4_iv -in mcserver-service-account-key.json.enc -out mod-managing/mcserver-service-account-key.json -d
- pip install -r requirements.txt
script:
- cd mod-managing
- python upload-mods.py
